"""TransformAgent: pure LLM transform with structured output."""
from __future__ import annotations

import json
from typing import Annotated, Any, Literal, Type

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, create_model, model_validator

from app.nodes.ai_task import LanguagePolicy
from app.nodes.base import NodeType
from app.nodes.data_transform import TransformOperation, _apply, _is_blank
from app.nodes.registry import NodeRegistry
from app.observability.logging import get_logger
from app.runtime.field_schema import (
    FieldSpec,
    build_response_model,
    describe_schema,
    field_paths,
    parse_fields,
)

log = get_logger(__name__)


class TransformInputField(BaseModel):
    """One named input the Prompt Template editor's Inputs section declares.

    `value` is always a `{{inputs.<name>}}` (or `{{outputs.<node>.<field>}}`)
    reference auto-generated by the Builder, never hand-typed — it is
    resolved to the real content by the executor's own template substitution
    before `run()` ever sees it, the same mechanism `AITaskConfig.context`
    already relies on.

    `value` is `Any`, not `str`: a bare `"{{a.b}}"` is whole-value template
    syntax (see app.runtime.templating.resolve), which preserves type rather
    than stringifying. Two consequences: an optional workflow input that
    wasn't supplied at run time resolves to `None` rather than `""`, and a
    reference into a JSON-typed workflow input or an upstream node's object/
    list-shaped output field (e.g. `{{inputs.proposal_blueprint.
    specific_objectives_table}}`) resolves to a real dict/list, not a string.
    A `str` annotation would reject both with a raw pydantic error naming a
    config key the workflow author never typed. `_new_style_user_prompt`
    renders the value for the model: a string as-is, `None` as `""` (matching
    how the legacy embedded `{{inputs.x}}` syntax always treated an
    unresolved optional reference as an empty gap rather than the word
    "None"), and anything else as pretty-printed JSON.
    """

    model_config = ConfigDict(extra="forbid")

    name: str
    description: str = ""
    type: str = "string"
    value: Any = ""


class TransformConfig(BaseModel):
    #: "ai" (default) is this node's original LLM-call behaviour, unchanged.
    #: "deterministic" runs the same 14 no-model operations DataTransformAgent
    #: does (copy/format/join/coalesce/object/select/number/boolean/…) — the
    #: two node types converge on one config schema here rather than one
    #: needing to duplicate the other's logic; DataTransformAgent itself stays
    #: registered and untouched for existing workflows.
    mode: Literal["ai", "deterministic"] = "ai"
    model: str = "claude-sonnet-4-5"
    #: Legacy hand-authored fields (raw prompt text with embedded `{{...}}`
    #: references). Optional so a new-style node (declares `instructions`
    #: instead) doesn't need to carry a dummy value — see `is_new_style`.
    prompt_template: str | None = None
    system_prompt: str | None = None
    output_schema: dict[str, str] = Field(default_factory=dict)
    #: New-style authoring fields, driving the Builder's Inputs/Instructions/
    #: Outputs editor. A node uses exactly one style — see `is_new_style`.
    input_fields: list[TransformInputField] = Field(default_factory=list)
    instructions: str = ""
    output_fields: list[FieldSpec] = Field(default_factory=list)
    #: Multilingual behaviour for the new-style (Inputs/Instructions/Outputs)
    #: path — ported from AITaskAgent's LanguagePolicy, the one capability
    #: this node lost when authoring moved off the deprecated AITaskAgent.
    #: `None` (the default) means no language directive is added, preserving
    #: this node's exact prior behaviour for every existing instance.
    language: LanguagePolicy | None = None
    temperature: float = 0.2
    max_tokens: int = Field(default=16384, ge=256)
    max_retries: int = Field(default=1, ge=0, le=3)
    #: Default True preserves this node's original behaviour: exhausting
    #: retries on a structured-output failure raises. Set False for the same
    #: non-raising escape hatch AITaskAgent has — a downstream Decision/Router
    #: can then gate on `status` instead of the run crashing.
    fail_on_error: bool = True
    #: Deterministic-mode fields — identical semantics to DataTransformConfig.
    operations: list[TransformOperation] = Field(default_factory=list)
    omit_empty: bool = False

    @model_validator(mode="after")
    def has_a_prompt_source(self) -> "TransformConfig":
        if self.mode != "ai":
            return self
        if not self.instructions.strip() and not (self.prompt_template or "").strip():
            raise ValueError(
                "TransformAgent needs either `instructions` (Prompt Template "
                "editor) or a legacy `prompt_template`"
            )
        return self

    @model_validator(mode="after")
    def deterministic_mode_has_operations(self) -> "TransformConfig":
        if self.mode != "deterministic":
            return self
        if not self.operations:
            raise ValueError(
                "TransformAgent in deterministic mode needs at least one "
                "operation"
            )
        targets = [op.target for op in self.operations]
        duplicates = sorted({name for name in targets if targets.count(name) > 1})
        if duplicates:
            raise ValueError(
                f"transform writes {duplicates} more than once; each target "
                "must be assigned by exactly one operation"
            )
        return self


def is_new_style(cfg: TransformConfig) -> bool:
    """Whether this node was authored through the Inputs/Instructions/Outputs
    editor rather than with a hand-written `prompt_template`.

    The single discriminator shared by `run()`, the preflight hooks below and
    `app.runtime.logic_preflight.transform_agent_paths` — keeping it in one
    place is what keeps those three from disagreeing about a node's shape.
    """
    return bool(cfg.instructions.strip())


def _render_input_value(value: Any) -> str:
    """Render one resolved input field's value for embedding in the prompt.

    A workflow input or upstream field can resolve to a plain string, `None`
    (an unsupplied optional), or a whole object/list (a JSON-typed workflow
    input, or an upstream node's structured output field). JSON — not
    Python's `str(dict)` repr — is what makes the object/list case readable
    to the model instead of a wall of single-quoted Python syntax.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False, indent=2, default=str)


class TransformInput(BaseModel):
    pass


class TransformOutput(BaseModel):
    raw: str
    parsed: dict[str, Any]
    #: "ok" unless `fail_on_error=False` and structured-output validation
    #: never succeeded — mirrors AITaskOutput's status enum so a downstream
    #: Decision/Router can gate on either node type's output the same way.
    status: Literal["ok", "refused", "invalid_output", "provider_error"] = "ok"
    error: str | None = None
    #: Deterministic-mode result — identical shape to DataTransformOutput.
    #: Always present (empty when mode="ai") so a template reference to
    #: `{{this_node.data}}` authorises regardless of mode.
    data: dict[str, Any] = Field(default_factory=dict)
    defaulted: list[str] = Field(default_factory=list)


def _decode_json_container(value: Any) -> Any:
    """Decode a JSON object or array returned inside a string.

    Some models occasionally return a nested tool argument like:

        {
            "ssh": "{\"status\":\"PARTIAL\",\"gaps\":[]}"
        }

    The outer response is valid, but ssh is still a string. This validator
    converts it back into a dictionary before final Pydantic validation.
    """
    if not isinstance(value, str):
        return value

    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return value


JsonStringList = Annotated[
    list[str],
    BeforeValidator(_decode_json_container),
]

JsonObject = Annotated[
    dict[str, Any],
    BeforeValidator(_decode_json_container),
]


_TYPE_MAP: dict[str, Any] = {
    "str": str,
    "string": str,
    "int": int,
    "integer": int,
    "float": float,
    "number": float,
    "bool": bool,
    "boolean": bool,
    "list": JsonStringList,
    "dict": JsonObject,
    "object": JsonObject,
}


def _build_response_model(
    name: str,
    schema: dict[str, str],
) -> Type[BaseModel]:
    fields: dict[str, Any] = {}

    for key, type_str in schema.items():
        py_type = _TYPE_MAP.get(type_str.lower(), str)
        fields[key] = (py_type, ...)

    return create_model(
        name,
        **fields,
    )  # type: ignore[call-overload]


@NodeRegistry.register
class TransformAgent(NodeType):
    type_name = "TransformAgent"
    description = (
        "Pure LLM transform: summarize, classify, rewrite, extract."
    )
    input_schema = TransformInput
    output_schema = TransformOutput
    config_schema = TransformConfig

    @classmethod
    def required_services(cls, config: dict[str, Any]) -> set[str]:
        if config.get("mode") == "deterministic":
            return set()
        return {"llm", "cost_ledger"}

    @classmethod
    def preflight_output_fields(cls, config: dict[str, Any]) -> set[str]:
        # Every static TransformOutput field (raw, parsed, status, error,
        # data, defaulted) is always a legal bare reference, regardless of
        # mode — mirrors AITaskAgent's `declared = set(AITaskOutput.
        # model_fields)` so a template reference to `{{this_node.status}}`
        # authorises the same way on either node type.
        declared = set(TransformOutput.model_fields)
        if config.get("mode") == "deterministic":
            targets = {
                op.get("target")
                for op in (config.get("operations") or [])
                if isinstance(op, dict) and op.get("target")
            }
            return declared | {f"data.{name}" for name in targets}
        if bool((config.get("instructions") or "").strip()):
            try:
                fields = parse_fields(config.get("output_fields") or [])
            except Exception:
                # A malformed schema is reported by config validation with a
                # far better message than anything this hook could produce.
                return declared
            if not fields:
                return declared
            return declared | {f"parsed.{item.path}" for item in field_paths(fields)}
        output_schema = config.get("output_schema") or {}
        return declared | {f"parsed.{key}" for key in output_schema}

    @classmethod
    def preflight_static_output_values(cls, config: dict[str, Any]) -> dict[str, Any]:
        # run() hardcodes "parsed": {} whenever no output shape is declared —
        # a bare {{this_node.parsed}} reference is then guaranteed to
        # substitute an empty object forever, regardless of what the LLM
        # actually returns.
        if config.get("mode") == "deterministic":
            if not (config.get("operations") or []):
                return {"data": {}}
            return {}
        if bool((config.get("instructions") or "").strip()):
            if not (config.get("output_fields") or []):
                return {"parsed": {}}
            return {}
        if not (config.get("output_schema") or {}):
            return {"parsed": {}}
        return {}

    async def run(
        self,
        state,
        resolved_config: dict[str, Any],
    ) -> dict[str, Any]:
        cfg = TransformConfig(**resolved_config)
        if cfg.mode == "deterministic":
            return self._run_deterministic(cfg, state)
        llm = self.services["llm"]
        if is_new_style(cfg):
            return await self._run_new_style(cfg, llm)
        return await self._run_legacy(cfg, llm)

    # -- deterministic path (identical semantics to DataTransformAgent) ----

    def _run_deterministic(self, cfg: TransformConfig, state: Any) -> dict[str, Any]:
        context = dict(state)
        data: dict[str, Any] = {}
        defaulted: list[str] = []

        for op in cfg.operations:
            value = _apply(op, context)
            if _is_blank(value) and op.default is not None:
                value = op.default
                defaulted.append(op.target)
            if cfg.omit_empty and value is None:
                continue
            data[op.target] = value

        return {
            "raw": "",
            "parsed": {},
            "status": "ok",
            "error": None,
            "data": data,
            "defaulted": defaulted,
        }

    # -- legacy path (hand-authored prompt_template/system_prompt/output_schema) --

    async def _run_legacy(self, cfg: TransformConfig, llm: Any) -> dict[str, Any]:
        system = cfg.system_prompt or ""

        if not cfg.output_schema:
            response = await llm.complete(
                model=cfg.model,
                system=system,
                user=cfg.prompt_template,
                temperature=cfg.temperature,
                max_tokens=cfg.max_tokens,
            )

            return {
                "raw": response.text,
                "parsed": {},
            }

        response_model = _build_response_model(
            f"{self.node_id}_Output",
            cfg.output_schema,
        )

        prompt = cfg.prompt_template
        last_error: Exception | None = None
        total_attempts = cfg.max_retries + 1

        for attempt in range(1, total_attempts + 1):
            try:
                instance = await llm.complete_structured(
                    model=cfg.model,
                    system=system,
                    user=prompt,
                    response_model=response_model,
                    temperature=cfg.temperature,
                    max_tokens=cfg.max_tokens,
                )

                parsed = instance.model_dump(mode="python")

                return {
                    "raw": json.dumps(
                        parsed,
                        ensure_ascii=False,
                    ),
                    "parsed": parsed,
                }

            except Exception as error:
                last_error = error

                log.warning(
                    "transform.structured_attempt_failed",
                    node_id=self.node_id,
                    attempt=attempt,
                    total_attempts=total_attempts,
                    error=str(error),
                )

                if attempt < total_attempts:
                    prompt = (
                        f"{cfg.prompt_template}\n\n"
                        "CORRECTION REQUIRED: The previous structured "
                        "response did not match the required schema. "
                        "Return every field using its native JSON type. "
                        "Return objects as JSON objects and lists as JSON "
                        "arrays. Do not put JSON inside quoted strings.\n"
                        f"Validation error: {error}"
                    )

        if cfg.fail_on_error:
            raise RuntimeError(
                f"TransformAgent '{self.node_id}' failed to produce valid "
                f"structured output after {total_attempts} attempt(s): "
                f"{last_error}"
            ) from last_error
        return self._failure_result(last_error)

    # -- new-style path (Inputs/Instructions/Outputs editor) --------------

    async def _run_new_style(self, cfg: TransformConfig, llm: Any) -> dict[str, Any]:
        system = self._new_style_system_prompt(cfg)
        user = self._new_style_user_prompt(cfg)

        if not cfg.output_fields:
            response = await llm.complete(
                model=cfg.model,
                system=system,
                user=user,
                temperature=cfg.temperature,
                max_tokens=cfg.max_tokens,
            )
            return {
                "raw": response.text,
                "parsed": {},
            }

        response_model = build_response_model(
            cfg.output_fields, model_name=f"{self.node_id}_Output"
        )
        return await self._complete_structured_with_retries(
            llm,
            model=cfg.model,
            system=system,
            user=user,
            response_model=response_model,
            temperature=cfg.temperature,
            max_tokens=cfg.max_tokens,
            max_retries=cfg.max_retries,
            fail_on_error=cfg.fail_on_error,
        )

    def _new_style_system_prompt(self, cfg: TransformConfig) -> str:
        parts = [
            "You are a precise business-process assistant inside an "
            "automated workflow. Your output is consumed by deterministic "
            "business rules, not by a person reading prose.",
        ]
        if cfg.language is not None:
            parts.append(cfg.language.directive())
        if cfg.output_fields:
            parts.append(
                "Return every field of the required structure. The field "
                "descriptions below define what each one means:\n"
                + describe_schema(cfg.output_fields)
            )
            parts.append(
                "Never fabricate a value to fill a required field. Use "
                "null, an empty list, or the schema's catch-all value, and "
                "say so if you are asked to explain your reasoning."
            )
        if cfg.system_prompt and cfg.system_prompt.strip():
            parts.append(cfg.system_prompt.strip())
        return "\n\n".join(part for part in parts if part.strip())

    def _new_style_user_prompt(self, cfg: TransformConfig) -> str:
        blocks: list[str] = []
        if cfg.input_fields:
            lines = [
                f"{field.name}: {_render_input_value(field.value)}"
                for field in cfg.input_fields
            ]
            blocks.append("# Inputs\n" + "\n".join(lines))
        blocks.append(cfg.instructions.strip())
        return "\n\n".join(block for block in blocks if block.strip())

    def _failure_result(self, error: Exception) -> dict[str, Any]:
        """The non-raising counterpart to the two `RuntimeError`s above —
        only reachable when `fail_on_error=False`. "invalid_output" is the
        one status this failure mode can actually produce (schema validation
        never succeeded); "refused"/"provider_error" exist on the shared
        enum for parity with AITaskOutput but aren't distinguishable here."""
        return {
            "raw": "",
            "parsed": {},
            "status": "invalid_output",
            "error": str(error)[:500],
        }

    async def _complete_structured_with_retries(
        self,
        llm: Any,
        *,
        model: str,
        system: str,
        user: str,
        response_model: Type[BaseModel],
        temperature: float,
        max_tokens: int,
        max_retries: int,
        fail_on_error: bool = True,
    ) -> dict[str, Any]:
        prompt = user
        last_error: Exception | None = None
        total_attempts = max_retries + 1

        for attempt in range(1, total_attempts + 1):
            try:
                instance = await llm.complete_structured(
                    model=model,
                    system=system,
                    user=prompt,
                    response_model=response_model,
                    temperature=temperature,
                    max_tokens=max_tokens,
                )

                parsed = instance.model_dump(mode="python")

                return {
                    "raw": json.dumps(parsed, ensure_ascii=False),
                    "parsed": parsed,
                }

            except Exception as error:
                last_error = error

                log.warning(
                    "transform.structured_attempt_failed",
                    node_id=self.node_id,
                    attempt=attempt,
                    total_attempts=total_attempts,
                    error=str(error),
                )

                if attempt < total_attempts:
                    prompt = (
                        f"{user}\n\n"
                        "CORRECTION REQUIRED: The previous structured "
                        "response did not match the required schema. "
                        "Return every field using its native JSON type. "
                        "Return objects as JSON objects and lists as JSON "
                        "arrays. Do not put JSON inside quoted strings.\n"
                        f"Validation error: {error}"
                    )

        if fail_on_error:
            raise RuntimeError(
                f"TransformAgent '{self.node_id}' failed to produce valid "
                f"structured output after {total_attempts} attempt(s): "
                f"{last_error}"
            ) from last_error
        return self._failure_result(last_error)