import type { AgentActivity } from './businessChatModel';
import { api } from '../../../api/client';
import { speakText, speechSynthesisSupported, stopSpeaking } from './speech';

function statusGlyph(status: AgentActivity['status']): string {
  if (status === 'completed') return '✓';
  if (status === 'reused') return '↻';
  if (status === 'failed') return '×';
  if (status === 'needs_input') return '!';
  if (status === 'running') return '●';
  return '○';
}

function initials(name: string): string {
  return name.split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase();
}

export function AgentActivityCard({
  activity,
  selected,
  onSelect,
}: {
  activity: AgentActivity;
  selected: boolean;
  onSelect: () => void;
}) {
  const running = activity.status === 'running';
  return (
    <article
      data-node-id={activity.nodeId}
      className={`group flex max-w-3xl gap-3 rounded-xl px-3 py-3 transition ${
        selected ? 'bg-accent-50 ring-1 ring-accent-200' : 'hover:bg-slate-50'
      }`}
      onClick={onSelect}
      onKeyDown={event => {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          onSelect();
        }
      }}
      role="button"
      tabIndex={0}
      aria-label={`Inspect ${activity.displayName}`}
    >
      <div className="flex h-8 w-8 flex-none items-center justify-center rounded-full bg-slate-900 text-[10px] font-semibold text-white">
        {initials(activity.displayName)}
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
          <h3 className="text-sm font-semibold text-ink-900">{activity.displayName}</h3>
          {activity.agentRole && <span className="text-xs text-ink-400">{activity.agentRole}</span>}
          <span className={`text-xs ${activity.status === 'failed' ? 'text-bad' : running ? 'text-accent-600' : 'text-ink-400'}`}>
            {statusGlyph(activity.status)} {running ? 'Running' : activity.status.replace('_', ' ')}
          </span>
        </div>
        <p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-ink-700">{activity.text}</p>

        {activity.image && (
          <figure className="mt-3 max-w-md overflow-hidden rounded-xl border border-slate-200 bg-white">
            <img src={api.fileUrl(activity.image.key)} alt={`Generated by ${activity.image.provider}`} className="max-h-96 w-full object-contain" />
            <figcaption className="flex items-center justify-between gap-3 px-3 py-2 text-xs text-ink-500">
              <span>{activity.image.provider}{activity.image.model ? ` · ${activity.image.model}` : ''}</span>
              <a href={api.fileUrl(activity.image.key, true)} className="font-medium text-accent-700 hover:underline">Download</a>
            </figcaption>
          </figure>
        )}

        {activity.tool && (
          <details className="mt-2 text-xs" onClick={event => event.stopPropagation()}>
            <summary className="cursor-pointer list-none text-ink-500 hover:text-ink-800">
              {activity.tool.kind === 'web' ? '🌐' : activity.tool.kind === 'mcp' ? '🔌' : '📚'} {activity.tool.label}
              {activity.tool.detail ? ` · ${activity.tool.detail}` : ''}
              {activity.sources?.length ? ' · View sources' : ' · Details'}
            </summary>
            {activity.sources && activity.sources.length > 0 && (
              <ol className="mt-2 space-y-1 rounded-lg border border-slate-200 bg-white p-3">
                {activity.sources.map((source, index) => (
                  <li key={`${source.title}-${index}`} className="truncate">
                    {source.url
                      ? <a href={source.url} target="_blank" rel="noreferrer" className="text-accent-700 hover:underline">{source.title}</a>
                      : source.title}
                  </li>
                ))}
              </ol>
            )}
          </details>
        )}

        {activity.route && (
          <p className="mt-2 text-xs text-ink-500">Route selected automatically · Select this message to inspect the decision.</p>
        )}

        {activity.error && (
          <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">
            <p>{activity.error}</p>
            {activity.recoveryActions.length > 0 && (
              <p className="mt-2">Suggested next actions: {activity.recoveryActions.join(' · ')}</p>
            )}
            <details className="mt-2">
              <summary className="cursor-pointer text-amber-700">View technical error</summary>
              <pre className="mt-1 overflow-x-auto whitespace-pre-wrap">{activity.error}</pre>
            </details>
          </div>
        )}

        <div className="mt-2 flex items-center gap-3 text-[11px] text-ink-400 opacity-0 transition group-hover:opacity-100 group-focus-within:opacity-100">
          <button type="button">{activity.durationSeconds != null ? `${activity.durationSeconds.toFixed(1)}s · ` : ''}Details</button>
          {typeof window !== 'undefined' && speechSynthesisSupported() && (
            <>
              <button type="button" onClick={event => { event.stopPropagation(); speakText(activity.text); }}>🔊 Read aloud</button>
              <button type="button" onClick={event => { event.stopPropagation(); stopSpeaking(); }}>Stop</button>
            </>
          )}
        </div>
      </div>
    </article>
  );
}