"""Weaviate client and schema definition.

The schema (collection: DocumentChunk) is the contract between ingestion
and retrieval. Every property we want to filter on in Phase 3 must be
declared here. Adding properties later requires re-indexing.

We use vectorizer=none: embeddings are generated by our embedder module
and passed in explicitly. This keeps embedding logic portable across
vector stores.
"""
from __future__ import annotations

from typing import Any

import weaviate
from weaviate.auth import Auth
from weaviate.classes.config import Configure, DataType, Property
from weaviate.collections.classes.data import DataObject
from weaviate.config import AdditionalConfig, Timeout

from app.config import settings
from app.observability.logging import get_logger

log = get_logger(__name__)

COLLECTION_NAME = "DocumentChunk"


# ---------- Schema definition -------------------------------------------------

SCHEMA_PROPERTIES = [
    Property(name="chunk_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="text", data_type=DataType.TEXT, index_searchable=True),
    Property(name="token_count", data_type=DataType.INT, index_filterable=True),
    Property(name="source_path", data_type=DataType.TEXT, index_filterable=True),
    Property(name="source_format", data_type=DataType.TEXT, index_filterable=True),
    Property(name="unit_index", data_type=DataType.INT, index_filterable=True),
    Property(name="unit_label", data_type=DataType.TEXT),
    Property(name="chunk_index", data_type=DataType.INT, index_filterable=True),
    Property(name="industry", data_type=DataType.TEXT, index_filterable=True),
    Property(name="doc_type", data_type=DataType.TEXT, index_filterable=True),
    Property(name="language", data_type=DataType.TEXT, index_filterable=True),
    Property(name="session_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="collection_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="display_number", data_type=DataType.INT, index_filterable=True),
    Property(name="ingested_at", data_type=DataType.DATE),
    # Knowledge Studio provenance/search-surface fields. Additive so legacy
    # objects (which predate these) simply read back null for them.
    Property(name="retrieval_content", data_type=DataType.TEXT, index_searchable=True),
    Property(name="context_content", data_type=DataType.TEXT),
    Property(name="title", data_type=DataType.TEXT, index_searchable=True),
    Property(name="section", data_type=DataType.TEXT, index_searchable=True),
    Property(name="page", data_type=DataType.INT, index_filterable=True),
    Property(name="index_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="document_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="source_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="source_version_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="parent_chunk_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="chunk_role", data_type=DataType.TEXT, index_filterable=True),
    Property(name="workspace_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="parser_profile_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="chunking_profile_id", data_type=DataType.TEXT, index_filterable=True),
    Property(name="embedding_profile_id", data_type=DataType.TEXT, index_filterable=True),
]


def ensure_collection_schema_on(client: weaviate.WeaviateClient, name: str) -> None:
    """Create ``name`` with the standard chunk schema if it doesn't exist yet.

    Takes an already-connected raw ``weaviate.WeaviateClient`` directly, so
    callers holding one (e.g. ``services["weaviate_client"]``, wired once at
    app startup) don't need a second connection through :class:`WeaviateClient`.
    Knowledge Studio indexes with a different embedding fingerprint get their
    own physical collection (``DocumentChunk_<fingerprint>``) so different
    vector dimensions never share one HNSW index.
    """
    if client.collections.exists(name):
        log.debug("weaviate.collection_exists", name=name)
        return
    client.collections.create(
        name=name,
        properties=SCHEMA_PROPERTIES,
        vector_config=Configure.Vectors.self_provided(
            vector_index_config=Configure.VectorIndex.hnsw(
                distance_metric=weaviate.classes.config.VectorDistances.COSINE,
            ),
        ),
    )
    log.info("weaviate.collection_created", name=name)


def upsert_objects_on(
    client: weaviate.WeaviateClient,
    collection_name: str,
    objects: list[dict[str, Any]],
    vectors: list[list[float]],
) -> int:
    """Batch-insert ``objects``/``vectors`` into ``collection_name``.

    Idempotent on ``chunk_id`` (the object UUID is derived from it). Returns
    the number of objects actually inserted, so the caller can detect a
    partial write.
    """
    if len(objects) != len(vectors):
        raise ValueError(f"objects/vectors length mismatch: {len(objects)} vs {len(vectors)}")
    collection = client.collections.get(collection_name)
    with collection.batch.dynamic() as batch:
        for obj, vector in zip(objects, vectors):
            batch.add_object(
                properties=obj, vector=vector, uuid=weaviate.util.generate_uuid5(obj["chunk_id"])
            )
    failed = collection.batch.failed_objects
    failed_count = len(failed) if failed else 0
    inserted = len(objects) - failed_count
    if failed_count > 0:
        for f in failed[:3]:
            log.error(
                "weaviate.upsert_error", message=getattr(f, "message", str(f)),
                obj=getattr(f, "object_", None),
            )
    log.info(
        "weaviate.upsert_done", collection=collection_name,
        inserted=inserted, errors=failed_count, total=len(objects),
    )
    return inserted


# ---------- Client lifecycle --------------------------------------------------


class WeaviateClient:
    """Thin wrapper around weaviate-client v4.

    Handles connection lifecycle and schema bootstrapping.
    Constructed once at app startup, closed at shutdown.
    """

    def __init__(self, url: str | None = None):
        self._url = url or f"http://{settings.weaviate_host}:{settings.weaviate_port}"
        self._client: weaviate.WeaviateClient | None = None

    def connect(self) -> weaviate.WeaviateClient:
        """Open the gRPC + REST connection. Call once at startup."""
        if self._client is not None:
            return self._client

        # Parse host/port from the URL
        from urllib.parse import urlparse
        parsed = urlparse(self._url)
        host = parsed.hostname or "weaviate"
        port = parsed.port or 8080

        self._client = weaviate.connect_to_custom(
            http_host=host,
            http_port=port,
            http_secure=parsed.scheme == "https",
            grpc_host=host,
            grpc_port=settings.weaviate_grpc_port,
            grpc_secure=False,
            auth_credentials=(
                Auth.api_key(settings.weaviate_api_key)
                if settings.weaviate_api_key
                else None
            ),
            additional_config=AdditionalConfig(
                timeout=Timeout(
                    init=settings.external_request_timeout_seconds,
                    query=settings.external_request_timeout_seconds,
                    insert=settings.external_request_timeout_seconds,
                )
            ),
        )
        log.info("weaviate.connected", host=host, port=port)
        return self._client

    def close(self) -> None:
        """Close the underlying gRPC channel. Call at app shutdown."""
        if self._client is not None:
            self._client.close()
            self._client = None
            log.info("weaviate.closed")

    # ---- Schema management ---------------------------------------------------

    def ensure_schema(self) -> None:
        """Create the DocumentChunk collection if it doesn't exist.

        Safe to call repeatedly. Does NOT migrate existing schemas — if the
        collection exists with different properties, we leave it alone and
        log a warning. Phase 11 will add a migration helper.
        """
        client = self.connect()
        if client.collections.exists(COLLECTION_NAME):
            log.debug("weaviate.collection_exists", name=COLLECTION_NAME)
            return

        client.collections.create(
            name=COLLECTION_NAME,
            properties=SCHEMA_PROPERTIES,
            # No server-side vectorizer; we pass vectors in explicitly.
            # HNSW index with cosine distance is the standard config for
            # OpenAI embeddings (they are normalized for cosine similarity).
            vector_config=Configure.Vectors.self_provided(
                vector_index_config=Configure.VectorIndex.hnsw(
                    distance_metric=weaviate.classes.config.VectorDistances.COSINE,
                ),
            ),
        )
        log.info("weaviate.collection_created", name=COLLECTION_NAME)

    def ensure_collection_schema(self, name: str) -> None:
        """Like :meth:`ensure_schema`, but for an arbitrary physical collection."""

        ensure_collection_schema_on(self.connect(), name)

    def upsert_objects(
        self, collection_name: str, objects: list[dict[str, Any]], vectors: list[list[float]]
    ) -> int:
        """Like :meth:`upsert_chunks`, but targeting an arbitrary physical collection."""

        return upsert_objects_on(self.connect(), collection_name, objects, vectors)

    def reset_schema(self) -> None:
        """DESTRUCTIVE: delete the collection and recreate it.

        Used in tests and during dev. Never call from production code.
        """
        client = self.connect()
        if client.collections.exists(COLLECTION_NAME):
            client.collections.delete(COLLECTION_NAME)
            log.warning("weaviate.collection_deleted", name=COLLECTION_NAME)
        self.ensure_schema()

    # ---- Data operations ----------------------------------------------------

    def upsert_chunks(
        self,
        chunks: list[dict[str, Any]],
        vectors: list[list[float]],
    ) -> int:
        """Insert or replace chunks. Idempotent on chunk_id.
        Each chunk dict must contain all schema properties. vectors[i] is the
        embedding for chunks[i]. Length mismatch raises ValueError.
        """
        if len(chunks) != len(vectors):
            raise ValueError(
                f"chunks/vectors length mismatch: {len(chunks)} vs {len(vectors)}"
            )

        client = self.connect()
        collection = client.collections.get(COLLECTION_NAME)

        # Weaviate v4 batch context: the `batch` object's stats are only
        # readable WHILE the context is open. Capture before exit.
        with collection.batch.dynamic() as batch:
            for chunk, vector in zip(chunks, vectors):
                batch.add_object(
                    properties=chunk,
                    vector=vector,
                    uuid=weaviate.util.generate_uuid5(chunk["chunk_id"]),
                )

        # After the `with` block, use the v4 helpers on the collection's batch
        # interface to read failure stats. `failed_objects` lists every failure
        # with its error message — much more useful than just a count.
        failed = collection.batch.failed_objects
        failed_count = len(failed) if failed else 0
        inserted = len(chunks) - failed_count

        if failed_count > 0:
            # Log the first few failures so the cause is visible without
            # dumping potentially huge lists to stdout.
            for f in failed[:3]:
                log.error(
                    "weaviate.upsert_error",
                    message=getattr(f, "message", str(f)),
                    obj=getattr(f, "object_", None),
                )

        log.info(
            "weaviate.upsert_done",
            inserted=inserted,
            errors=failed_count,
            total=len(chunks),
        )
        return inserted

    def count_chunks(self) -> int:
        """Total chunks in the collection. Useful for tests and diagnostics."""
        client = self.connect()
        collection = client.collections.get(COLLECTION_NAME)
        return collection.aggregate.over_all(total_count=True).total_count

    def add_property(self, prop: Property) -> None:
        """Non-destructive schema evolution. Old objects get null for new field."""
        collection = self.connect().collections.get(COLLECTION_NAME)
        collection.config.add_property(prop)
        log.info("weaviate.property_added", name=prop.name)
# ---------- Module-level singleton -------------------------------------------

_default_client: WeaviateClient | None = None


def get_weaviate_client() -> WeaviateClient:
    """Lazily-constructed module-level client. Use this from app code."""
    global _default_client
    if _default_client is None:
        _default_client = WeaviateClient()
        _default_client.connect()
        _default_client.ensure_schema()
    return _default_client
